### ISSUE TITLE
Client fetch error: Request is not defined

### ISSUE THREAD

**Issue by cacode-euan** [wobsoriano/fastify-next-auth#1]
When following the Client API example in the README, I get the below error when running getProviders and getCsrfToken

Any ideas on how to fix it?

![image](https://user-images.githubusercontent.com/84316323/188615046-1e4151af-1abb-4ece-9b7c-499da4442ddf.png)

**Comment by cacode-euan** [comment]
I was able to fix this by adding global.fetch = fetch. However, I still can't run the functions as I now get this error.
Weirdly, I am able to use the NextAuth REST API to call the the /auth/csrf route manually though

![image](https://user-images.githubusercontent.com/84316323/188618818-a7ce3133-4d6d-44b7-bb4f-7f2a86f646e7.png)

**Comment by wobsoriano** [comment]
Can you try v0.1.7 and reopen it if the issue still persists? Thanks!
